session: ${name}
root: ${root}

windows:
  - name: " "
    commands:
      - nvim
  - name: " "
    commands:
      - clear
  - name: " "
    commands:
      - nvim +DBUI
  - name: ""
    commands:
      - lazygit
  - name: " "
    commands:
      - opencode
